name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/site1/TyutyunShopFrontend || { echo "Не вдалося перейти в каталог."; exit 1; }

          echo "Оновлення коду з Git..."
          git pull || { echo "Не вдалося виконати git pull."; exit 1; }

          echo "Перебудова Docker образу..."
          docker build -t my-nginx-site .

          echo "Оновлення Docker контейнера..."
          docker exec my-nginx-container nginx -s reload || { echo "Не вдалося оновити контейнер."; exit 1; }

          echo "Оновлення завершено!"