name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/site1/TyutyunShopFrontend
          git pull
          docker build -t my-nginx-site .

          if docker ps -a --filter "name=my-nginx-container" -q; then
             docker stop my-nginx-container
             docker rm my-nginx-container
          fi
          docker run -d -p 8080:80 -p 8443:443 --name my-nginx-container my-nginx-site