name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
- name: Pull the latest changes from git repository
      run: |
        cd /var/www/site1/TyutyunShopFrontend
        git pull

    - name: Build Docker image
      run: |
        cd /var/www/site1/TyutyunShopFrontend
        docker build -t my-nginx-site .

    - name: Stop the running Docker container if exists
      run: |
        if docker ps -a --filter "name=my-nginx-container" -q; then
          docker stop my-nginx-container
        else
          echo "Container is not running"
        fi

    - name: Remove the old Docker container if exists
      run: |
        if docker ps -a --filter "name=my-nginx-container" -q; then
          docker rm my-nginx-container
        else
          echo "No container to remove"
        fi

    - name: Run new Docker container
      run: |
        docker run -d -p 8080:80 -p 8443:443 --name my-nginx-container my-nginx-site

    - name: Check if container is running
      run: |
        docker ps